// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalMonitoring.proto

package org.ruojiefan.smartcities;

public final class EnvironmentalMonitoringOuterClass {
  private EnvironmentalMonitoringOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnvironmentalConditionsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentalConditionsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Location to monitor environmental conditions
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    java.lang.String getLocation();
    /**
     * <pre>
     * Location to monitor environmental conditions
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * <pre>
   * Message for requesting environmental conditions monitoring
   * </pre>
   *
   * Protobuf type {@code EnvironmentalConditionsRequest}
   */
  public  static final class EnvironmentalConditionsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EnvironmentalConditionsRequest)
      EnvironmentalConditionsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvironmentalConditionsRequest.newBuilder() to construct.
    private EnvironmentalConditionsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvironmentalConditionsRequest() {
      location_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentalConditionsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.class, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    private volatile java.lang.Object location_;
    /**
     * <pre>
     * Location to monitor environmental conditions
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Location to monitor environmental conditions
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, location_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest)) {
        return super.equals(obj);
      }
      org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest other = (org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest) obj;

      boolean result = true;
      result = result && getLocation()
          .equals(other.getLocation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for requesting environmental conditions monitoring
     * </pre>
     *
     * Protobuf type {@code EnvironmentalConditionsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentalConditionsRequest)
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.class, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.Builder.class);
      }

      // Construct using org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        location_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsRequest_descriptor;
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest getDefaultInstanceForType() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest build() {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest buildPartial() {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest result = new org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest(this);
        result.location_ = location_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest) {
          return mergeFrom((org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest other) {
        if (other == org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest.getDefaultInstance()) return this;
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <pre>
       * Location to monitor environmental conditions
       * </pre>
       *
       * <code>string location = 1;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Location to monitor environmental conditions
       * </pre>
       *
       * <code>string location = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Location to monitor environmental conditions
       * </pre>
       *
       * <code>string location = 1;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Location to monitor environmental conditions
       * </pre>
       *
       * <code>string location = 1;</code>
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Location to monitor environmental conditions
       * </pre>
       *
       * <code>string location = 1;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EnvironmentalConditionsRequest)
    }

    // @@protoc_insertion_point(class_scope:EnvironmentalConditionsRequest)
    private static final org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest();
    }

    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvironmentalConditionsRequest>
        PARSER = new com.google.protobuf.AbstractParser<EnvironmentalConditionsRequest>() {
      @java.lang.Override
      public EnvironmentalConditionsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentalConditionsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvironmentalConditionsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentalConditionsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnvironmentalConditionsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentalConditionsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    java.util.List<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition> 
        getConditionDataList();
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition getConditionData(int index);
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    int getConditionDataCount();
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    java.util.List<? extends org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder> 
        getConditionDataOrBuilderList();
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder getConditionDataOrBuilder(
        int index);

    /**
     * <pre>
     * Additional metadata or status information
     * </pre>
     *
     * <code>string status = 2;</code>
     */
    java.lang.String getStatus();
    /**
     * <pre>
     * Additional metadata or status information
     * </pre>
     *
     * <code>string status = 2;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * <pre>
   * Message for environmental conditions response
   * </pre>
   *
   * Protobuf type {@code EnvironmentalConditionsResponse}
   */
  public  static final class EnvironmentalConditionsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EnvironmentalConditionsResponse)
      EnvironmentalConditionsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvironmentalConditionsResponse.newBuilder() to construct.
    private EnvironmentalConditionsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvironmentalConditionsResponse() {
      conditionData_ = java.util.Collections.emptyList();
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentalConditionsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                conditionData_ = new java.util.ArrayList<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition>();
                mutable_bitField0_ |= 0x00000001;
              }
              conditionData_.add(
                  input.readMessage(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          conditionData_ = java.util.Collections.unmodifiableList(conditionData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.class, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CONDITIONDATA_FIELD_NUMBER = 1;
    private java.util.List<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition> conditionData_;
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    public java.util.List<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition> getConditionDataList() {
      return conditionData_;
    }
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    public java.util.List<? extends org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder> 
        getConditionDataOrBuilderList() {
      return conditionData_;
    }
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    public int getConditionDataCount() {
      return conditionData_.size();
    }
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition getConditionData(int index) {
      return conditionData_.get(index);
    }
    /**
     * <pre>
     * Environmental conditions data for the requested location
     * </pre>
     *
     * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
     */
    public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder getConditionDataOrBuilder(
        int index) {
      return conditionData_.get(index);
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <pre>
     * Additional metadata or status information
     * </pre>
     *
     * <code>string status = 2;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Additional metadata or status information
     * </pre>
     *
     * <code>string status = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < conditionData_.size(); i++) {
        output.writeMessage(1, conditionData_.get(i));
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < conditionData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, conditionData_.get(i));
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse)) {
        return super.equals(obj);
      }
      org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse other = (org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse) obj;

      boolean result = true;
      result = result && getConditionDataList()
          .equals(other.getConditionDataList());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getConditionDataCount() > 0) {
        hash = (37 * hash) + CONDITIONDATA_FIELD_NUMBER;
        hash = (53 * hash) + getConditionDataList().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for environmental conditions response
     * </pre>
     *
     * Protobuf type {@code EnvironmentalConditionsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentalConditionsResponse)
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.class, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.Builder.class);
      }

      // Construct using org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConditionDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (conditionDataBuilder_ == null) {
          conditionData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          conditionDataBuilder_.clear();
        }
        status_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalConditionsResponse_descriptor;
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse getDefaultInstanceForType() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse build() {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse buildPartial() {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse result = new org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (conditionDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            conditionData_ = java.util.Collections.unmodifiableList(conditionData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.conditionData_ = conditionData_;
        } else {
          result.conditionData_ = conditionDataBuilder_.build();
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse) {
          return mergeFrom((org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse other) {
        if (other == org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse.getDefaultInstance()) return this;
        if (conditionDataBuilder_ == null) {
          if (!other.conditionData_.isEmpty()) {
            if (conditionData_.isEmpty()) {
              conditionData_ = other.conditionData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConditionDataIsMutable();
              conditionData_.addAll(other.conditionData_);
            }
            onChanged();
          }
        } else {
          if (!other.conditionData_.isEmpty()) {
            if (conditionDataBuilder_.isEmpty()) {
              conditionDataBuilder_.dispose();
              conditionDataBuilder_ = null;
              conditionData_ = other.conditionData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              conditionDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConditionDataFieldBuilder() : null;
            } else {
              conditionDataBuilder_.addAllMessages(other.conditionData_);
            }
          }
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition> conditionData_ =
        java.util.Collections.emptyList();
      private void ensureConditionDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          conditionData_ = new java.util.ArrayList<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition>(conditionData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder> conditionDataBuilder_;

      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public java.util.List<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition> getConditionDataList() {
        if (conditionDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(conditionData_);
        } else {
          return conditionDataBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public int getConditionDataCount() {
        if (conditionDataBuilder_ == null) {
          return conditionData_.size();
        } else {
          return conditionDataBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition getConditionData(int index) {
        if (conditionDataBuilder_ == null) {
          return conditionData_.get(index);
        } else {
          return conditionDataBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder setConditionData(
          int index, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition value) {
        if (conditionDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionDataIsMutable();
          conditionData_.set(index, value);
          onChanged();
        } else {
          conditionDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder setConditionData(
          int index, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder builderForValue) {
        if (conditionDataBuilder_ == null) {
          ensureConditionDataIsMutable();
          conditionData_.set(index, builderForValue.build());
          onChanged();
        } else {
          conditionDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder addConditionData(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition value) {
        if (conditionDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionDataIsMutable();
          conditionData_.add(value);
          onChanged();
        } else {
          conditionDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder addConditionData(
          int index, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition value) {
        if (conditionDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConditionDataIsMutable();
          conditionData_.add(index, value);
          onChanged();
        } else {
          conditionDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder addConditionData(
          org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder builderForValue) {
        if (conditionDataBuilder_ == null) {
          ensureConditionDataIsMutable();
          conditionData_.add(builderForValue.build());
          onChanged();
        } else {
          conditionDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder addConditionData(
          int index, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder builderForValue) {
        if (conditionDataBuilder_ == null) {
          ensureConditionDataIsMutable();
          conditionData_.add(index, builderForValue.build());
          onChanged();
        } else {
          conditionDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder addAllConditionData(
          java.lang.Iterable<? extends org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition> values) {
        if (conditionDataBuilder_ == null) {
          ensureConditionDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, conditionData_);
          onChanged();
        } else {
          conditionDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder clearConditionData() {
        if (conditionDataBuilder_ == null) {
          conditionData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          conditionDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public Builder removeConditionData(int index) {
        if (conditionDataBuilder_ == null) {
          ensureConditionDataIsMutable();
          conditionData_.remove(index);
          onChanged();
        } else {
          conditionDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder getConditionDataBuilder(
          int index) {
        return getConditionDataFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder getConditionDataOrBuilder(
          int index) {
        if (conditionDataBuilder_ == null) {
          return conditionData_.get(index);  } else {
          return conditionDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public java.util.List<? extends org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder> 
           getConditionDataOrBuilderList() {
        if (conditionDataBuilder_ != null) {
          return conditionDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(conditionData_);
        }
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder addConditionDataBuilder() {
        return getConditionDataFieldBuilder().addBuilder(
            org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.getDefaultInstance());
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder addConditionDataBuilder(
          int index) {
        return getConditionDataFieldBuilder().addBuilder(
            index, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.getDefaultInstance());
      }
      /**
       * <pre>
       * Environmental conditions data for the requested location
       * </pre>
       *
       * <code>repeated .EnvironmentalCondition conditionData = 1;</code>
       */
      public java.util.List<org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder> 
           getConditionDataBuilderList() {
        return getConditionDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder> 
          getConditionDataFieldBuilder() {
        if (conditionDataBuilder_ == null) {
          conditionDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder>(
                  conditionData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          conditionData_ = null;
        }
        return conditionDataBuilder_;
      }

      private java.lang.Object status_ = "";
      /**
       * <pre>
       * Additional metadata or status information
       * </pre>
       *
       * <code>string status = 2;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Additional metadata or status information
       * </pre>
       *
       * <code>string status = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Additional metadata or status information
       * </pre>
       *
       * <code>string status = 2;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional metadata or status information
       * </pre>
       *
       * <code>string status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional metadata or status information
       * </pre>
       *
       * <code>string status = 2;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EnvironmentalConditionsResponse)
    }

    // @@protoc_insertion_point(class_scope:EnvironmentalConditionsResponse)
    private static final org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse();
    }

    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvironmentalConditionsResponse>
        PARSER = new com.google.protobuf.AbstractParser<EnvironmentalConditionsResponse>() {
      @java.lang.Override
      public EnvironmentalConditionsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentalConditionsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvironmentalConditionsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentalConditionsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnvironmentalConditionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentalCondition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Timestamp of the environmental condition data
     * </pre>
     *
     * <code>string timestamp = 1;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     * Timestamp of the environmental condition data
     * </pre>
     *
     * <code>string timestamp = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     * Type of environmental condition (e.g., temperature, humidity)
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     * Type of environmental condition (e.g., temperature, humidity)
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * Value of the environmental condition
     * </pre>
     *
     * <code>float value = 3;</code>
     */
    float getValue();
  }
  /**
   * <pre>
   * Message to represent environmental condition data
   * </pre>
   *
   * Protobuf type {@code EnvironmentalCondition}
   */
  public  static final class EnvironmentalCondition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EnvironmentalCondition)
      EnvironmentalConditionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvironmentalCondition.newBuilder() to construct.
    private EnvironmentalCondition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvironmentalCondition() {
      timestamp_ = "";
      type_ = "";
      value_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentalCondition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 29: {

              value_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalCondition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalCondition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.class, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     * Timestamp of the environmental condition data
     * </pre>
     *
     * <code>string timestamp = 1;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Timestamp of the environmental condition data
     * </pre>
     *
     * <code>string timestamp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     * Type of environmental condition (e.g., temperature, humidity)
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Type of environmental condition (e.g., temperature, humidity)
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private float value_;
    /**
     * <pre>
     * Value of the environmental condition
     * </pre>
     *
     * <code>float value = 3;</code>
     */
    public float getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestamp_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (value_ != 0F) {
        output.writeFloat(3, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestamp_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (value_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition)) {
        return super.equals(obj);
      }
      org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition other = (org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition) obj;

      boolean result = true;
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && getType()
          .equals(other.getType());
      result = result && (
          java.lang.Float.floatToIntBits(getValue())
          == java.lang.Float.floatToIntBits(
              other.getValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message to represent environmental condition data
     * </pre>
     *
     * Protobuf type {@code EnvironmentalCondition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentalCondition)
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalConditionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalCondition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalCondition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.class, org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.Builder.class);
      }

      // Construct using org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = "";

        type_ = "";

        value_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.internal_static_EnvironmentalCondition_descriptor;
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition getDefaultInstanceForType() {
        return org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.getDefaultInstance();
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition build() {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition buildPartial() {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition result = new org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition(this);
        result.timestamp_ = timestamp_;
        result.type_ = type_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition) {
          return mergeFrom((org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition other) {
        if (other == org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition.getDefaultInstance()) return this;
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getValue() != 0F) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       * Timestamp of the environmental condition data
       * </pre>
       *
       * <code>string timestamp = 1;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Timestamp of the environmental condition data
       * </pre>
       *
       * <code>string timestamp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Timestamp of the environmental condition data
       * </pre>
       *
       * <code>string timestamp = 1;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp of the environmental condition data
       * </pre>
       *
       * <code>string timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp of the environmental condition data
       * </pre>
       *
       * <code>string timestamp = 1;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Type of environmental condition (e.g., temperature, humidity)
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Type of environmental condition (e.g., temperature, humidity)
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Type of environmental condition (e.g., temperature, humidity)
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of environmental condition (e.g., temperature, humidity)
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of environmental condition (e.g., temperature, humidity)
       * </pre>
       *
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private float value_ ;
      /**
       * <pre>
       * Value of the environmental condition
       * </pre>
       *
       * <code>float value = 3;</code>
       */
      public float getValue() {
        return value_;
      }
      /**
       * <pre>
       * Value of the environmental condition
       * </pre>
       *
       * <code>float value = 3;</code>
       */
      public Builder setValue(float value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Value of the environmental condition
       * </pre>
       *
       * <code>float value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EnvironmentalCondition)
    }

    // @@protoc_insertion_point(class_scope:EnvironmentalCondition)
    private static final org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition();
    }

    public static org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvironmentalCondition>
        PARSER = new com.google.protobuf.AbstractParser<EnvironmentalCondition>() {
      @java.lang.Override
      public EnvironmentalCondition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentalCondition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvironmentalCondition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentalCondition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ruojiefan.smartcities.EnvironmentalMonitoringOuterClass.EnvironmentalCondition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentalConditionsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnvironmentalConditionsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentalConditionsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnvironmentalConditionsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentalCondition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnvironmentalCondition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035EnvironmentalMonitoring.proto\"2\n\036Envir" +
      "onmentalConditionsRequest\022\020\n\010location\030\001 " +
      "\001(\t\"a\n\037EnvironmentalConditionsResponse\022." +
      "\n\rconditionData\030\001 \003(\0132\027.EnvironmentalCon" +
      "dition\022\016\n\006status\030\002 \001(\t\"H\n\026EnvironmentalC" +
      "ondition\022\021\n\ttimestamp\030\001 \001(\t\022\014\n\004type\030\002 \001(" +
      "\t\022\r\n\005value\030\003 \001(\0022\251\003\n\027EnvironmentalMonito" +
      "ring\022e\n\036MonitorEnvironmentalConditions\022\037" +
      ".EnvironmentalConditionsRequest\032 .Enviro" +
      "nmentalConditionsResponse\"\000\022a\n!Continuou" +
      "sEnvironmentalMonitoring\022\037.Environmental" +
      "ConditionsRequest\032\027.EnvironmentalConditi" +
      "on\"\0000\001\022^\n\035StreamEnvironmentalConditions\022" +
      "\027.EnvironmentalCondition\032 .Environmental" +
      "ConditionsResponse\"\000(\001\022d\n\"InteractiveEnv" +
      "ironmentalMonitoring\022\037.EnvironmentalCond" +
      "itionsRequest\032\027.EnvironmentalCondition\"\000" +
      "(\0010\001B\033\n\031org.ruojiefan.smartcitiesb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnvironmentalConditionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnvironmentalConditionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnvironmentalConditionsRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_EnvironmentalConditionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnvironmentalConditionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnvironmentalConditionsResponse_descriptor,
        new java.lang.String[] { "ConditionData", "Status", });
    internal_static_EnvironmentalCondition_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnvironmentalCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnvironmentalCondition_descriptor,
        new java.lang.String[] { "Timestamp", "Type", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
